config/routes.rb
Rails.application.routes.draw do
  root "couriers#index"

  resources :couriers do
    resources :packages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, length: { minimum: 4 }
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  def index
    @couriers = Courier.all
  end

  def show
    @courier = Courier.find(params[:id])
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render :new
    end
  end

  def edit
    @courier = Courier.find(params[:id])
  end

  def update
    @courier = Courier.find(params[:id])

    if @courier.update(courier_params)
      redirect_to @courier
    else
      render :edit
    end
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy

    redirect_to root_path
  end

  private
    def courier_params
      params.require(:courier).permit(:name, :email, :status)
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def create
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.create(package_params)
    redirect_to courier_path(@courier)
  end

  def destroy
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.find(params[:id])
    @package.destroy
    redirect_to courier_path(@courier)
  end

  private
    def package_params
      params.require(:package).permit(:tracking_number, :delivery_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.erb
<%= form_with model: courier do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% courier.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% courier.errors.full_messages_for(:email).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>
                                                                        

app/views/couriers/edit.html.erb
<h1>Edit Courier</h1>

<%= render "form", courier: @courier %>

app/views/couriers/index.html.erb
<h1>Couriers</h1>

<ul>
  <% @couriers.each do |courier| %>
      <li>
        <%= link_to courier.name, courier %>
      </li>
  <% end %>
</ul>

<%= link_to "New Courier", new_courier_path %>

app/views/couriers/new.html.erb
<h1>New Article</h1>

<%= render "form", courier: @courier %>

app/views/couriers/show.html.erb
<h1><%= @courier.name %></h1>

<p><%= @courier.email %></p>

<ul>
  <li><%= link_to "Edit", edit_courier_path(@courier) %></li>
  <li><%= link_to "Destroy", courier_path(@courier),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>


<h2>Packages</h2>
<%= render @courier.packages %>

<h2>Add a comment:</h2>
<%= render 'packages/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>